# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'srinivasnines docker hub'
        repository: 'srinivasnines/weagtherapi'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: '$(tag)'
-  stage: Provision
   displayName: "Terrforming on Azure...."
   depends: Build
   jobs:
   - job: Provision
     displayName: 'Provisioning Container Instance'
     pool:
        vMImage: ubunutu-latest'
     variables:
      - group: TerraformEnvVars
      steps:
      - scripts: |
           set -e

           terraform init -input=false
           terraform apply -input=false -auto-approve
        name: 'Run Terraform'
        displayname: 'Run Terraform'
        env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          ARM_TENANT_ID: $(ARM_TENANT_ID)


setx ARM_TENANT_ID f845842e-ecc0-4ba1-914f-1d0b05eb9d8e

setx ARM_CLIENT_SECRET qn77Q~pAu17NOq1U-xucoOfYd6gafmboUcUlA

setx ARM_SUBSCRIPTION_ID 4b72053c-658d-4365-bbbf-018da39975e1


b62ac3b4-798d-4182-98d7-bfeb9008d440


 